<?php 

$list = array(
	"!Silent",
	"!SilentTest",
	"+Electricity",
	"029Ab",
	"79a",
	"88marcus",
	"A.WagnerC",
	"Acdallago",
	"Acscosta",
	"Adailton",
	"AdriAg",
	"Afavoritaweb",
	"Aflis",
	"Agent010",
	"Agiesbrecht",
	"Agnyeszka",
	"Agronopolos",
	"Aisteco",
	"Ajmcbarreto",
	"Ajpvalente",
	"Antonio Prates",
	"Aolynthon",
	"ApoloFebo",
	"Archaeodontosaurus",
	"ArgonSim",
	"ArionEstar",
	"Armagedon2000",
	"Arouck",
	"Arthemius x",
	"Artur Domingos",
	"Ary29",
	"Aspargos",
	"Athena in Wonderland",
	"Augusto Reynaldo Caetano Shereiber",
	"Aviz2000",
	"Awikimate",
	"B.Lameira",
	"BOT-vinnik",
	"Bad Boy97",
	"Bafuncius",
	"Bageense",
	"Barão de Itararé",
	"Belanidia",
	"Berganus",
	"Beria",
	"Berthold Werner",
	"Betty VH",
	"Beyondit",
	"BigLordFlash",
	"Biologo32",
	"Bisbis",
	"Blamed",
	"Bolhones",
	"Bonifácio",
	"Borowskki",
	"Brandizzi",
	"Brazuka!",
	"Bruna 1999",
	"Bruno Luiz da Costa Bulhões",
	"Bruno Meireles",
	"Bruno N. Campos",
	"Bruno Ramos Uehara",
	"Brunonar",
	"Brítez",
	"BunnyyHop",
	"Burmeister",
	"Bya97",
	"CCosta (WMB)",
	"CS1982",
	"Cadnero",
	"Cainamarques",
	"Caio Brandão Costa",
	"Caio!",
	"CaiusSPQR",
	"CalliandraDysantha",
	"Camervan",
	"Capmo",
	"Carlos Luis M C da Cruz",
	"Carlos28",
	"CarlosCunha",
	"Carlírio Neto",
	"Carrion",
	"Casnouto",
	"Cassio Sabacão",
	"Castelobranco",
	"Caçador de Palavras",
	"Cdmafra",
	"Ceresta",
	"Cesarakg",
	"Chairhandlers",
	"Chapulinaaa",
	"Charles keen",
	"Chebellatopa",
	"Chico",
	"Chicocvenancio",
	"ChristianH",
	"Chronus",
	"Cidcn",
	"Cignenoire",
	"Citizen Kimi",
	"Clarice Reis",
	"Claudio M Souza",
	"Claudio Pistilli",
	"Cléééston",
	"Coelhomiq",
	"Colaborador 2.542",
	"Coltsfan",
	"CommonsDelinker",
	"Comuna de Paris",
	"Conde Ed Dantes",
	"Conde Edmond Dantès",
	"Conde de Morcerf",
	"Conrado",
	"Contaminadas",
	"Contreiras45",
	"CorreiaPM",
	"CostaPPPR",
	"Crabbe o Editor",
	"Curiapeba",
	"Cyberlima785",
	"Cósmico",
	"DAR7",
	"DARIO SEVERI",
	"DanGFSouza",
	"Daniel Cavallari",
	"Daniel Schröder",
	"Daniel.Vitor1",
	"DanielFreitas",
	"DanielTom",
	"Danielly Campos Dias",
	"Danilo.mac",
	"Danilomath",
	"Dantadd",
	"DanteCan",
	"DarkWerewolf",
	"DarwIn",
	"Dbastro",
	"Defender",
	"Dennylson Adam",
	"Dianakc",
	"Didifelisberto",
	"Diego Carvalho",
	"Diego Queiroz",
	"Dilcinha",
	"Dilermando",
	"Dioluisf",
	"DmitryN",
	"DocElisa",
	"Domusaurea",
	"Dornicke",
	"Douglasboavista",
	"Doutorgrillo",
	"Dr. Lenaldo Vigo",
	"Dravinia",
	"DreamNight",
	"Dreispt",
	"Duduzimm",
	"Duke of Winterfell",
	"DutchDevil",
	"Dux Praxis",
	"EAzzellini (WMB)",
	"EPorto (WMB)",
	"EUDOXIO",
	"EVinente",
	"Eamaral",
	"Eazy-P",
	"Econt",
	"Ederporto",
	"Edissom",
	"Editor D.S",
	"Editor Master Plus",
	"Edu!",
	"Eduardo Kazuo",
	"Eduardo Pazos",
	"EduardoFP7",
	"Edviges",
	"El Descamisado",
	"Elder N",
	"Eleefecosta",
	"Elilopes",
	"Elvedi",
	"EnaldoSS",
	"Epinheiro",
	"Eric Duff",
	"Eric abiog",
	"EricaAzzellini",
	"Erick Soares3",
	"Erico Tachizawa",
	"Escoria79",
	"Esopo",
	"EternamenteAprendiz",
	"EuTuga",
	"Everton137",
	"Ezco Musaos",
	"FSogumo",
	"Fabiano Tatsch",
	"Fabiobarros",
	"Fabiojrsouza",
	"Fabsouza1",
	"Faduart",
	"Faltur",
	"Fasouzafreitas",
	"Feen",
	"Feldmann",
	"Feliciomendes",
	"Felipe P",
	"Felipe da Fonseca",
	"Felipe.moraislima",
	"Femme Fatale",
	"Fernandobrasilien",
	"Fernandokaiserbr",
	"Fgnievinski",
	"FilipeFalcão",
	"Filipeschaves",
	"Filtro de edições",
	"Flávia Varella",
	"Fma",
	"Fox de Quintal",
	"Frajolex",
	"FrancisAkio",
	"Francisco Leandro",
	"Francisco Quiumento",
	"FranciscoMG",
	"FrontLine",
	"Fronteira",
	"Fsantos222",
	"Fulviusbsas",
	"Furious97",
	"Fúlvio",
	"G.M",
	"GABS",
	"GFontenelle (WMB)",
	"GUROMETAL",
	"Gabriel C",
	"Gabriel Francisco GFSW",
	"Gabriel Guilherme",
	"Gabriel Yuji",
	"Gabriel bier",
	"Gabriel dos Santos",
	"GabrielStella",
	"Gabrielrs",
	"Gameiro",
	"Gato Preto",
	"Gean",
	"Geobage",
	"Georgez",
	"Geovani.s",
	"Gerbilo",
	"GhostP.",
	"GiFontenelle",
	"Giloliveira1994",
	"Giorgione62",
	"Girassolei",
	"Giro720",
	"Giullia Duarte Almeida",
	"Gjpab",
	"GoEThe",
	"Gremista.32",
	"Grind24",
	"GualdimG",
	"Guilherme",
	"Gunnex",
	"Gustave London",
	"Gustaveb",
	"Gustavo Rogalewski",
	"Gustavo Siqueira",
	"Gustavo gho",
	"Gustavotcabral",
	"GünniX",
	"HCa",
	"HVL",
	"Hallel",
	"He7d3r",
	"Hedestad",
	"Hedwig in Washington",
	"Heitor",
	"Helder Monter",
	"HenriqueCrang",
	"Hererightnow",
	"Hermógenes Teixeira Pinto Filho",
	"Hgh1993",
	"Hipersyl",
	"Hlges",
	"Hml.sdi",
	"Hqfngawz",
	"Hume42",
	"Hunz",
	"Hyju",
	"Hímeros",
	"IacobusBr",
	"Igor G.Monteiro",
	"Igordebraga",
	"Imagens SM",
	"Instambul",
	"Isabelle Belato",
	"Ishiai",
	"Ismael Silva Oliveira",
	"Iuri i10",
	"Ixocactus",
	"J. A. S. Ferreira",
	"JBarreto",
	"JCMA",
	"JJ Cuela",
	"JMSilva",
	"JMagalhães",
	"JPeschanski (WMB)",
	"Jack Bauer00",
	"JackCrazy5",
	"Jackgba",
	"Jackson Cordeiro Brilhador",
	"Jadolfo",
	"Jaideraf",
	"Jairinho",
	"Jamadruga",
	"Japf",
	"JardelW",
	"Jasão",
	"Jbribeiro1",
	"JeanVitorSouza",
	"Jebelmir",
	"JeffBruno",
	"Jefferson055",
	"Jesielt",
	"Jflabreu",
	"Jhonnycach",
	"Jimmy.T.",
	"Jin-gook",
	"Jmvkrecords",
	"Jo Lorib",
	"JoJan",
	"Joalpe",
	"Joao0Paulo",
	"Joao4669",
	"Joaovitorbf",
	"Joelkaula",
	"JohnR",
	"Johnny Paes",
	"Jolielegal",
	"JonJon86",
	"Jonas kam",
	"JonasBR",
	"Josegalego",
	"Joseolgon",
	"José João Salles",
	"José Luís Ávila Silveira",
	"José Tadeu Barros",
	"JotaCartas",
	"JozeSlb",
	"João Carvalho",
	"João Justiceiro",
	"João Sousa",
	"João Victor Costa",
	"João Xavier",
	"JoãoGuilherme68",
	"Joãofcf",
	"Joémerson Maia",
	"Jsneto",
	"Jsobral",
	"Juan90264",
	"Judcosta",
	"Junior Silva Rodriguess",
	"Juntas",
	"Jurisdictio",
	"KDL527",
	"Kaktus Kid",
	"Kascyo",
	"Keijuu",
	"Kelvin Samuel",
	"Keplerbr",
	"Kim richard",
	"King of Prussia",
	"KiraTHO",
	"Kleiner",
	"Kongs",
	"",
	"",
	"",
	"",
	"Kwangya",
	"L'editeur",
	"L'Éclipse",
	"L-0395",
	"LF337",
	"LP Sérgio LP",
	"LPrati",
	"LTeles (WMF)",
	"La marionnette",
	"Laczkowski",
	"Lagape",
	"Lauro Chieza de Carvalho",
	"Leandro Drudo",
	"Leandro LV",
	"Leandrod",
	"Lechatjaune",
	"Leefeni de Karik",
	"Lemarlou",
	"LeoAShima",
	"LeoFaria",
	"Leoherdy",
	"Leonardorejorge",
	"Leone Melo",
	"Leosls",
	"Leszek Jańczuk",
	"Levs",
	"Leytor",
	"Liege",
	"Lijealso",
	"Lina Yab",
	"Liquet",
	"LodeRunner",
	"Loidez",
	"Lord Mota",
	"Lordcaio",
	"Lorde McCoy",
	"Lourencoalmada",
	"Lsn11",
	"Luan",
	"LuanCampSouza93",
	"LuanSP",
	"Luandersonplayplay2",
	"Lucas Landin",
	"Lucas S.C.",
	"Lucas Secret",
	"Lucas.Belo",
	"Lucas11925",
	"LucasFVenturini",
	"LucasT.Aquino",
	"Lucasmf23",
	"Lucaspdantas",
	"Lucio Luiz",
	"Lucs1994",
	"Ludmilson",
	"Luiz F. Fritz",
	"Luiz265",
	"Luizdl",
	"Luizengmec",
	"Luizpuodzius",
	"Luk3",
	"Luks25",
	"Lustmoon",
	"Luz28",
	"MCarrera (NeuroMat)",
	"MOC",
	"MSN12102001",
	"MachoCarioca",
	"Mad Fox",
	"Maddox",
	"Madmarioni",
	"MagicSenna",
	"Magioladitis",
	"Maikê",
	"Maisonneuve",
	"Malafaya",
	"Mandorake",
	"Manope2011",
	"Manuel Anastácio",
	"Manuel de Sousa",
	"Manuelvbotelho",
	"Maragm",
	"Marcelo Henrique Bittencourt",
	"Marcelo Victor",
	"Marcelportugal",
	"Marcia Beatriz Einsfeld",
	"Marcoasxd",
	"Marcosfaria70",
	"Marcric",
	"Marcus Cyron",
	"Marcus274",
	"MariaCastell",
	"Mariordo",
	"Marquinhos",
	"Mars Rover",
	"Mary Eleanor de Normandy",
	"Matemágico",
	"Materialscientist",
	"Mateus RM",
	"Mateussf",
	"Mateusthunder",
	"Matheus Camcho",
	"MatheusMtHs",
	"Mathonius",
	"Mawer10",
	"Max51",
	"Maxtremus",
	"MayTheForce",
	"Mayckon.trudes",
	"Mbassis",
	"Mcorrlo",
	"Mecanismo",
	"MelM",
	"Meriade",
	"Micael 106",
	"Michaelpires",
	"Mig Ling",
	"MiguelMadeira",
	"Miguelrangeljr",
	"MikaelSilveira",
	"Mike Peel",
	"Mikebarross",
	"MikutoH",
	"Milca jnr",
	"Minerva97",
	"MisterSanderson",
	"Mizunoryu",
	"Moretti",
	"Mr. Fulano",
	"Mrzero",
	"Mschlindwein",
	"MuriloHDD",
	"Music01",
	"Mwaldeck",
	"Mário NET",
	"N4TR!UMbr",
	"NAMmc2",
	"NMaia",
	"Nakinn",
	"Naldo Arruda",
	"Naner Wikipedista",
	"Nanny321",
	"Nelson R. de Lima Filho",
	"NelsonCM",
	"Neofox-san",
	"Neomoses",
	"Net Esportes",
	"Nevinho",
	"Nice poa",
	"Niegodzisie",
	"Ninux2000",
	"Nistelrooy",
	"NonSecta",
	"Norris",
	"NosLida",
	"Nuno Raimundo",
	"Nuno Tavares",
	"Nyvak",
	"O Sem Autoridade",
	"O revolucionário aliado",
	"OTAVIO1981",
	"Observatore",
	"OffsBlink",
	"OnlyJonny",
	"Oona",
	"Opaulo",
	"Opraco",
	"Orchi",
	"Osmaludo",
	"Oursana",
	"Outis",
	"Ovelhamauro",
	"Ozymandias",
	"P.H.SPFC",
	"PH.testes",
	"PViz",
	"Pablo Busatto",
	"Pablodiego15",
	"Palaciano",
	"Paladinum2",
	"Parzeus",
	"Pascoal IV",
	"Pathoschild",
	"Patricia CV",
	"PatríciaR",
	"PauloEduardo",
	"PauloHenrique",
	"PauloMSimoes",
	"Paz e concórdia",
	"PedR",
	"Pedrassani",
	"Pedro Aguiar",
	"Pedro Jorge",
	"Pedro Me.",
	"PedroCosta",
	"PedroPVZ",
	"Pedrohoneto",
	"Pedu0303",
	"Pereira Pedro",
	"Pgnm",
	"Phill ad",
	"Pi bot",
	"Picknick",
	"Pilgerowski",
	"Pinhelense",
	"Pintopc",
	"Polemaco",
	"Porantim",
	"Porto Mineiro",
	"Pqnonwba",
	"Praxidicae",
	"Prima.philosophia",
	"ProntComando",
	"Psem25832",
	"Pwoli",
	"Py4nf",
	"Pássaro do Sol",
	"Qualquerumxx",
	"Raafael",
	"Rachmaninoff",
	"RadiX",
	"RafaAzevedo",
	"Rafael Kenneth",
	"Rafazmr",
	"Raimundo57br",
	"Raphael Figueira",
	"Raphaelsmuniz",
	"Rathbone",
	"Raul Caarvalho",
	"Raylton P. Sousa",
	"Red123",
	"Regi-Iris Stefanelli",
	"Rei Momo",
	"Renan Rabbit",
	"Renato de carvalho ferreira",
	"Renzo Grosso",
	"Reporter",
	"Retornaire",
	"Rgps",
	"Rhodes00",
	"Ricardo Ferreira de Oliveira",
	"Ricardo L1ma",
	"Ricarlos Almagro",
	"Richvianbonett",
	"RickMorais",
	"Ricvelozo",
	"Rmv1",
	"Robertogilnei",
	"Robson correa de camargo",
	"Rockysantos",
	"Rodrigo Padula",
	"RodrigoAndradet",
	"Rodrigoan",
	"Rodrigogomesonetwo",
	"Rodrigolopes",
	"RodsTR",
	"Roger Otoni",
	"Romaine",
	"RonaldB",
	"Roni1986",
	"Rui Gabriel Correia",
	"Rumanovsk",
	"Rush",
	"Rzyck",
	"Ródi",
	"Rúdisicyon",
	"SBanksX",
	"SEPRodrigues",
	"Sage (Wiki Ed)",
	"Sagotreespirit",
	"SallesNeto BR",
	"Sampayu",
	"Sarah Pereira Marcelino",
	"Sarilho1",
	"Sartius",
	"Saturnalia0",
	"Scheridon",
	"Scott Tomlinson",
	"Sepguilherme",
	"Sergio Kaminski",
	"Sethemanuel",
	"Simplus Menegati",
	"Sir Lestaty de Lioncourt",
	"SirEdimon",
	"Skartaris",
	"Skeptikós",
	"Slade",
	"Slaytanic",
	"Solstag",
	"Sorocabano 32",
	"Spartacus.",
	"Sphynx-SN",
	"Spoladore",
	"Stangbot",
	"Stanglavine",
	"Stego",
	"Stegop",
	"Stephan1000000",
	"Sturm",
	"Sudhertzen",
	"Summerzith",
	"Superplástico",
	"Swblade",
	"Swendt",
	"Sylvio Sant",
	"TaahCaaroline",
	"Taba1964",
	"Taketa",
	"Tawan Silva Mendes",
	"Teixant",
	"Teles",
	"Tetizeraz",
	"Tetraktys",
	"Tfda tapro",
	"The Joker",
	"The WWE man",
	"TheCrazy",
	"Theocfar",
	"Theodoxa",
	"Theys York",
	"Thiago MTB",
	"ThiagoEFreitas",
	"ThiagoRuiz",
	"ThrasherÜbermensch",
	"Tiago de Jesus Neves",
	"TiagoLubiana",
	"Tiburcio43",
	"Tintazul",
	"Titoncio",
	"Tks4Fish",
	"Tonyjeff",
	"Torsade de Pointes",
	"Totodu74",
	"Trierweiller",
	"Tschis",
	"Tuga1143",
	"Tuga9890",
	"Tuvalkin",
	"Um simples Wikipedista",
	"Umberto Bottura",
	"Ungolo",
	"UrsoBR",
	"User7778",
	"Usien6",
	"UsuárioPar",
	"Uxbona",
	"Valberto Silva",
	"ValterVB",
	"Vanthorn",
	"Vargenau",
	"VdSV9",
	"Viatoribus",
	"Vicinis",
	"Victor Andrade",
	"Victor Lopes",
	"Vinctus",
	"Vini 175",
	"Vinicius Lima",
	"ViniciusBR11",
	"Vitor Mazuco",
	"Vitor12345",
	"Vitruviano",
	"Vituzzu",
	"Volenski",
	"VítoR Valente",
	"W.SE",
	"WBV1986",
	"WMFOffice",
	"WOtP",
	"WPTBR",
	"Waldyrious",
	"Wallinson",
	"Warley Felipe C.S.",
	"Webysther",
	"Weslen Fillipe",
	"WiFábio",
	"Wiforst",
	"WikiFer",
	"Wikimasterbz",
	"Wilberty",
	"Wsdantas",
	"Xandi",
	"Xaosflux",
	"Xavier1824",
	"Xico CLJ",
	"Xutzão",
	"Xuxo",
	"Yanguas",
	"Yasméssica",
	"Ygor Alves",
	"YgorD3",
	"Yone Fernandes",
	"Young Brujah",
	"YuriNikolai",
	"Zac Salvatore",
	"ZackTheJack",
	"Zarco",
	"Zdtrlik",
	"Zehlu",
	"Zervim",
	"Zoldyick",
	"Épico",
	"Érico"
);

echo("<pre>");

foreach ($list as $user) {
	$api = file_get_contents("https://www.wikidata.org/w/api.php?action=query&format=json&list=usercontribs&uclimit=500&ucend=2021-04-10T00%3A00%3A00.000Z&ucuser=".urlencode($user));
	$api = json_decode($api, true);
	$api = count($api["query"]["usercontribs"]);
	echo("\"".$user."\";".$api."\n");
}